blog/urls.py
from django.urls import path
from .views import (HomePageView, ArticleListView, ArticleDetailView, 
                        ArticleUpdateView, ArticleDeleteView, ArticleCreateView) 

urlpatterns = [
    path('', HomePageView.as_view(), name="blog_home"), 
    path('articles/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('articles/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('articles/<int:pk>/edit/', ArticleUpdateView.as_view(), name='article_edit'),
    path('articles/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
    path('articles/new/', ArticleCreateView.as_view(), name='article_new'),
    path('articles', ArticleListView.as_view(), name='article_list'),
]
    

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),   
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),
    path('_admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import MainView

urlpatterns = [
    path('', MainView.as_view(), name='main'),
]

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField

User = get_user_model()


class Article(models.Model):
    title = models.CharField(max_length=150)
    summary = models.CharField(max_length=200, blank=True)
    body = RichTextField()
    photo = models.ImageField(upload_to='images/', blank=True)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article_detail', args=[str(self.id)])


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    comment = models.CharField(max_length=150)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('article_list')

main/models.py
from django.db import models
from django.utils import timezone
from uuid import uuid4


class Home(models.Model):
	title = models.CharField(max_length=128, blank=False, null=False)
	description = models.TextField(max_length=2048, blank=True, null=True)

	def __str__(self):
		return self.title

class About(models.Model):
	title = models.CharField(max_length=128, blank=False, null=False)
	description = models.TextField(max_length=2048, blank=True, null=True)
	image = models.ImageField(default=None, blank=True, null=True)

	def __str__(self):
		return self.title


class Menu(models.Model):
	def dp_rename_and_path(instance, filename):
		extension = filename.split('.')[-1]
		time_stamp = timezone.now()
		time_stamp = time_stamp.strftime("%d-%m-%Y_%I-%M-%S%p")
		path = 'menu_pics/{title}/{time_stamp}_{randomstring}.{extension}'.format(
			title = instance.title, 
			time_stamp = time_stamp, 
			randomstring = uuid4().hex, 
			extension = extension,
		)
		print(path)
		return path
		
	title = models.CharField(max_length=128, blank=False, null=False)
	price = models.CharField(max_length=64, blank=False, null=False)
	discount = models.CharField(max_length=64, blank=True, null=True)
	image = models.ImageField(default='menu_pics/default_menu.jpg', upload_to = dp_rename_and_path)
	
	def add_to_card(self, *args):
		pass

	def __str__(self):
		return self.title

class Products(models.Model):
	def dp_rename_and_path(instance, filename):
		extension = filename.split('.')[-1]
		time_stamp = timezone.now()
		time_stamp = time_stamp.strftime("%d-%m-%Y_%I-%M-%S%p")
		path = '{title}/{time_stamp}_{randomstring}.{extension}'.format(
			title = instance.title, 
			time_stamp = time_stamp, 
			randomstring = uuid4().hex, 
			extension = extension,
		)
		print(path)
		return path

	title = models.CharField(max_length=128, null=True, blank=True)
	price = models.CharField(max_length=64, blank=False, null=False)
	discount = models.CharField(max_length=64, blank=True, null=True)
	image = models.ImageField(default='products_pics/default_product.jpg', upload_to = dp_rename_and_path)

	def star(self, *args):
		pass
	
	def like(self, *args):
		pass

	def view(self, *args):
		pass

	def add_to_card(self, *args):
		pass

	def __str__(self):
		return self.title    


class Contact(models.Model):
	name = models.CharField(max_length=128, blank=False, null=False)
	email = models.EmailField(unique=True, blank=False, null=False)
	number = models.SmallIntegerField(unique=True)  
	review = models.TextField(max_length=2048, default=None) 
	check_display = models.BooleanField(default=False)

	def __str__(self):
		return self.name

main/forms.py
from django.forms import ModelForm
from .models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'number', 'review']

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy
from .models import Article


class HomePageView(TemplateView):
    template_name = 'blog/home.html'


class ArticleListView(ListView):
    model = Article
    template_name = 'blog/article_list.html'


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/article_detail.html'


class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Article
    fields = ('title', 'summary', 'body', 'photo')
    template_name = 'blog/article_edit.html'

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Article
    template_name = 'blog/article_delete.html'
    success_url = reverse_lazy('article_list')

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class ArticleCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Article
    template_name = 'blog/article_new.html'
    fields = ('title', 'summary', 'body', 'photo',)

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        return self.request.user.is_superuser

main/views.py
from django.shortcuts import render, redirect
from django.views import View

from .models import Home, About, Menu, Products, Contact
from .forms import ContactForm


class MainView(View): 
	def get(self, request):
		home = Home.objects.first()
		about = About.objects.first()
		menu = Menu.objects.all()
		products = Products.objects.all()
		contact  = Contact.objects.filter(check_display='True')
		return render(request, "index.html", {
			'home': home, 'about': about, 'menu': menu, 'products': products, 'contact': contact   
		})      
	
	def post(self, request):
		form = ContactForm(request.POST)

		if form.is_valid():
			data = form.cleaned_data
			print(data)
			print(type(data))
			Contact.objects.create(
				name=data["name"],
				email=data["email"],
				number=data["number"],
				review=data["review"]
			) 
			return redirect('main')
		else:
			print("error: Invalid")

		return render(request, "index.html", {
			"form": form,
		})
	

templates/blog/article_delete.html
{% extends 'blog/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="top_class">
        <h1>Postni o'chirish</h1>
        <form action="" method="post">{% csrf_token %}
            <p>"{{ article.title }}" nomli postni o'chirishni istaysizmi?</p>
        <button class="btn btn-danger ml-2" type="submit">ha</button>
        </form>
    </div>
{% endblock content %}

templates/blog/article_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container-fluid top_class">
        <div class="card" >
          <div class="card-body">
              {%  if object.photo %}
                <img class="card-img-top" src="{{ object.photo.url }}" alt="{{ object.title }}">
              {% endif %}
              <h1 class="card-title">{{ object.title }}</h1>
              <h6 class="card-subtitle mb-2 text-muted">Muallif: {{ object.author }} | {{ object.date }}</h6>
              <p class="card-text">{{ object.body | safe}}</p>
              <a href="{% url 'article_edit' article.pk %}">Tahrirlash</a> |
              <a href="{% url 'article_delete' article.pk %}">O'chirish</a> |
              <a href="{% url 'article_list' %}">Barcha postlar</a>
          </div>
            <div class="card">
                <div class="card-header">Izohlar</div>
                {%  for comment in article.comments.all %}
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <p>{{ comment }}</p>
                            <footer class="blockquote-footer">{{ comment.author }}</footer>
                        </blockquote>
                    </div>
                {% endfor %}
            </div>
        </div>
        <p></p>
    </div>
{% endblock content %}

templates/blog/article_edit.html
{% extends 'blog/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="top_class">
        <h1>Tahrirlash</h1>
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
        <button class="btn btn-info ml-2" type="submit">Saqlash</button>
        </form>
    </div>>
{% endblock content %}

templates/blog/article_list.html
{% extends 'blog/base.html' %}

{% block title %} Postlar {% endblock title %}

{% block content %}
		<!-- blogs section starts  -->
		<section class="blogs top_class" id="blogs">
			<h1 class="heading"> our <span>blogs</span> </h1>
			<div class="box-container">
				{% for article in object_list %}

					<div class="box">
						<div class="image">
							{% if article.photo %}
								<img class="card-img-top" src="{{ article.photo.url }}" alt="{{ article.title }}">
							{%  endif %}            </div>
						<div class="content">
							<a href="{% url 'article_detail' article.pk  %}" class="title">
								<h2>{{ article.title }}</h2>
							</a>
							<p> {{ article.summary }}... </p>
							<a href="{% url 'article_detail' article.pk  %}"class="btn">read more</a>
							<span class="text-muted">by admin {{ article.author | title }} / {{ article.date }}</span>
						</div>
					</div>
				{% endfor %}
			</div>
		</section>
{% endblock content %}

templates/blog/article_new.html
{% extends 'blog/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="top_class">
        <h1>Yangi post</h1>
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
        <button class="btn btn-success ml-2" type="submit">Saqlash</button>
        </form>
    </div>
{% endblock content %}

templates/blog/base.html
{% load static %}

{% block extrahead %}
	<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
	{{ block.super }}
{% endblock %}
	
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Freesh Coffee</title>

	<!-- Bootstrap link  -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	
	<!-- font awesome cdn link  -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

	<!-- custom css file link  -->
	<link rel="stylesheet" href="/static/products/css/style.css">

</head>
<body>
	
<!-- header section   -->

<header class="header">

	<a href="{% url 'main' %}" class="logo">
		<img src="/static/products/images/logo.png" alt="Cafena Logo">
	</a>

	<nav class="navbar">
		<a href="{% url 'main' %}">home</a>
		<a href="{% url 'main' %}">about</a>
		<a href="{% url 'main' %}">menu</a>
		<a href="{% url 'main' %}">products</a>
		<a href="{% url 'main' %}">review</a>
		<a href="{% url 'main' %}">contact</a>
		<a href="{% url 'blog_home' %}">blogs</a>
	</nav>
	
</header>
<main>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</main>
<!-- footer section  -->
<section class="footer">

        <div class="share">
            <a href="#" class="fab fa-facebook-f"></a>
            <a href="#" class="fab fa-twitter"></a>
            <a href="#" class="fab fa-instagram"></a>
            <a href="#" class="fab fa-linkedin"></a>
            <a href="#" class="fab fa-pinterest"></a>
        </div>

		<div class="links">
			<a href="{% url 'main' %}">home</a>
			<a href="{% url 'main' %}">about</a>
			<a href="{% url 'main' %}">menu</a>
			<a href="{% url 'main' %}">products</a>
			<a href="{% url 'main' %}">review</a>
			<a href="{% url 'main' %}">contact</a>
			<a href="{% url 'main' %}">blogs</a>
		</div>
    
        <div class="credit">Copyright <span>©2022</span> | all rights reserved | created by <span>Ramazon</span></div>
    
    </section> 
    
    <!-- custom js file link  -->
    
    <script src="../../static/products/js/script.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

</body>
</html>

templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Bosh sahifa{% endblock title %}

{% block content %}
    <div class="top_class">
        <div class="jumbotron">
            <h1 class="display-4">Assalom alaykum!</h1>
            <p class="lead">Ramazon Zulfiqorovning shaxsiy blogiga xush kelibsiz.</p>
            <hr class="my-4">
            <p>Bu yerda siz dasturlash va dasturchilarga oid so'nggi yangiliklardan xabardor bo'lib turasiz.</p>
            <p class="lead">
                <a class="btn btn-primary btn-lg" href="{% url 'article_list' %}" role="button">Postlarni ko'rish</a>
            </p>
        </div>    
    </div> 
{% endblock content %}

templates/index.html
{% load static %}
{% load crispy_forms_tags %}	

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Delivery Food</title>

	<!-- font awesome cdn link  -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

	<!-- custom css file link  -->
	<link rel="stylesheet" href="/static/products/css/style.css">

</head>
<body>
	
<!-- header section starts  -->

<header class="header">

	<a href="{% url 'main' %}" class="logo">
		<img src="/static/products/images/logo5.jpg" alt="Cafena Logo">
	</a>

	<nav class="navbar">
		<a href="#home">home</a>
		<a href="#about">about</a>
		<a href="#menu">menu</a>
		<a href="#products">products</a>
		<a href="#review">review</a>
		<a href="#contact">contact</a>
		<a href="{% url 'blog_home' %}">blogs</a>
	</nav>

	<div class="icons">
		<div class="fas fa-search" id="search-btn"></div>
		<div class="fas fa-shopping-cart" id="cart-btn"></div>
		<div class="fas fa-bars" id="menu-btn"></div>
	</div>

	<div class="search-form">
		<input type="search" id="search-box" placeholder="search here...">
		<label for="search-box" class="fas fa-search"></label>
	</div>

	<div class="cart-items-container">
		<div class="cart-item">
			<span class="fas fa-times"></span>
			<img src="/static/products/images/cart-item-1.png" alt="">
			<div class="content">
				<h3>cart item 01</h3>
				<div class="price">$1.99/-</div>
			</div>
		</div>
		<div class="cart-item">
			<span class="fas fa-times"></span>
			<img src="../../static/products/images/cart-item-2.png" alt="">
			<div class="content">
				<h3>cart item 02</h3>
				<div class="price">$5.99/-</div>
			</div>
		</div>
		<div class="cart-item">
			<span class="fas fa-times"></span>
			<img src="/static/products/images/cart-item-3.png" alt="">
			<div class="content">
				<h3>cart item 03</h3>
				<div class="price">$2.99/-</div>
			</div>
		</div>
		<div class="cart-item">
			<span class="fas fa-times"></span>
			<img src="static/products/images/cart-item-4.png" alt="">
			<div class="content">
				<h3>cart item 04</h3>
				<div class="price">$4.99/-</div>
			</div>
		</div>
		<a href="#" class="btn">checkout now</a>
	</div>

</header>

<!-- header section ends -->

<!-- home section starts  -->

<section class="home" id="home">

	<div class="content">
		<h3>{{ home.title }}</h3>
		<p>{{ home.description }}</p>
		<a href="#menu" class="btn">get yours now</a>
	</div>

</section>

<!-- home section ends -->

<!-- about section starts  -->

<section class="about" id="about">

	<h1 class="heading"> <span>about</span> us </h1>

	<div class="row">

		<div class="image">
			<img src="/static/products/images/about-img.jpeg" alt="">
		</div>

		<div class="content">
			<h3>{{ about.title }}</h3>
			<p>{{ about.description }}</p>
			<a href="{% url 'blog_home' %}" class="btn">learn more</a>
		</div>

	</div>

</section>

<!-- about section ends -->

<!-- menu section starts  -->

<section class="menu" id="menu">

	<h1 class="heading"> our <span>menu</span> </h1>

	<div class="box-container">

	{% for item in menu %}
		<div class="box">
			<img src="{{ item.image.url }}" alt="Menu Coffee">
			<h3> {{ item.title }}</h3>
			<div class="price">{{ item.price }}<span>{{ item.discount }}</span></div>
			<a href="#" class="btn">add to cart</a>
		</div>
	{% endfor %}

	</div>

</section>

<!-- menu section ends -->

<section class="products" id="products">

	<h1 class="heading"> our <span>products</span> </h1>

	<div class="box-container">
	{% for product in products %}	
		<div class="box">
			<div class="icons">
				<a href="#" class="fas fa-shopping-cart"></a>
				<a href="#" class="fas fa-heart"></a>
				<a href="#" class="fas fa-eye"></a>
			</div>
			<div class="image">
				<img src="{{ product.image.url }}" alt="Product Coffee">
			</div>
			<div class="content">
				<h3>{{ product.title }}</h3>
				<div class="stars">
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star"></i>
					<i class="fas fa-star-half-alt"></i>
				</div>
				<div class="price">$ {{ product.price }} <span>${{ product.discount }}</span></div>
			</div>
		</div>
	{% endfor %}	

	</div>

</section>

<!-- review section starts  -->

<section class="review" id="review">

	<h1 class="heading"> customer's <span>review</span> </h1>

	<div class="box-container">

		{% for user in contact %}
				<div class="box">
					<img src="/static/products/images/quote-img.png" alt="" class="quote">
					<p>{{ user.review }}</p>
					<img src="/static/products/images/awatar.jpg" class="user" alt="">
					<h3>{{ user.name }}</h3>
					<div class="stars">
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star"></i>
						<i class="fas fa-star-half-alt"></i>
					</div>
				</div>
		{% endfor %}
	
		
	</div>

</section>

<!-- review section ends -->

<!-- contact section starts  -->

<section class="contact" id="contact">

	<h1 class="heading"> <span>contact</span> us </h1>

	<div class="row">

		<iframe class="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d30153.788252261566!2d72.82321484621745!3d19.141690214227783!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7b63aceef0c69%3A0x2aa80cf2287dfa3b!2sJogeshwari%20West%2C%20Mumbai%2C%20Maharashtra%20400047!5e0!3m2!1sen!2sin!4v1629452077891!5m2!1sen!2sin" allowfullscreen="" loading="lazy"></iframe>

		<form method="post"> 
			<h3>get in touch</h3>

			{% csrf_token %}

			<div id="div_id_name inputBox" class="form-group">
				<span class="fas fa-user"></span>
				<input type="text" name="name" maxlength="128" placeholder="name" class="textinput textInput form-control" required id="id_name"> 
			</div> 

			<div id="div_id_email" class="form-group"> 
				<span class="fas fa-envelope"></span>
				<input type="email" name="email" maxlength="254" placeholder="email" class="emailinput form-control" required id="id_email"> 
				
			</div> 

			<div id="div_id_number" class="form-group"> 
				<span class="fas fa-phone"></span>
				<div> 
					<input type="number" name="number" placeholder="number" class="numberinput form-control" required id="id_number">
				</div> 
			</div> 

			<div id="div_id_review" class="form-group"> 
				<span class="fas fa-comment-alt"></span>
				<div> 
					<textarea name="review" cols="40" placeholder="write review about coffe" rows="5" maxlength="2048" class="textarea form-control" required id="id_review"></textarea> 
				</div> 
			</div>
			
			<input type="submit" value="contact now" class="btn btn-primary">  

		</form> 

	</div>

</section>

<!-- contact section ends -->

<!-- footer section starts  -->

<section class="footer">

	<div class="share">
		<a href="#" class="fab fa-telegram"></a>
		<a href="#" class="fab fa-instagram"></a>
		<a href="#" class="fab fa-linkedin"></a>
	</div>

	<div class="links">
		<a href="#home">home</a>
		<a href="#about">about</a>
		<a href="#menu">menu</a>
		<a href="#products">products</a>
		<a href="#review">review</a>
		<a href="#contact">contact</a>
		<a href="#blog">blogs</a>
	</div>

	<div class="credit">Copyright <span>©2022</span> | all rights reserved | created by <span>Ramazon</span></div>

</section>

<!-- footer section ends -->

<!-- custom js file link  -->

<script src="/static/products/js/script.js"></script>

</body>
</html>